sh ./scripts/exp2/hdfs_cl_bert_both_sup0.0_epoch20.sh
sh ./scripts/exp2/hdfs_cl_bert_both_sup0.2_epoch20.sh
sh ./scripts/exp2/hdfs_cl_bert_both_sup0.4_epoch20.sh
sh ./scripts/exp2/hdfs_cl_bert_both_sup0.6_epoch20.sh
sh ./scripts/exp2/hdfs_cl_bert_both_sup0.8_epoch20.sh
sh ./scripts/exp2/hdfs_cl_bert_both_sup1.0_epoch20.sh
sh ./scripts/exp2/bgl_cl_bert_both_sup0.0_epoch20.sh
sh ./scripts/exp2/bgl_cl_bert_both_sup0.2_epoch20.sh
sh ./scripts/exp2/bgl_cl_bert_both_sup0.4_epoch20.sh
sh ./scripts/exp2/bgl_cl_bert_both_sup0.6_epoch20.sh
sh ./scripts/exp2/bgl_cl_bert_both_sup0.8_epoch20.sh
sh ./scripts/exp2/bgl_cl_bert_both_sup1.0_epoch20.sh